freebsd_task:
  name: FreeBSD CI
  only_if: $CIRRUS_BRANCH == 'master' && $CIRRUS_REPO_OWNER == 'oshi'
  skip: "!changesInclude('.cirrus.yml', '**/freebsd/**', '**/common/**', '**/unix/*', '**/util/**')"
  freebsd_instance:
    matrix:
      image_family: freebsd-14-3
      image_family: freebsd-15-0-amd64-ufs
  maven_cache:
    folder: ~/.m2
  install_script: pkg install -y openjdk11
  test_script: ./mvnw test -Djacoco.skip=true -B
