codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 70%
