# Full CI matrix on all pushes to master branch
name: macOS CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

permissions:
  contents: read

jobs:
  # Runs full project on multiple JDKs
  testmatrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Previous LTS, Current LTS, Current release
        java: [21, 25, 26]
        os: [macos-14, macos-15, macos-26]
        include:
          - java: 21
            os: 'macos-26-intel'
      fail-fast: false
    name: JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Test with Maven
        if: ${{ !contains(matrix.java, '25') }}
        run: ./mvnw clean test -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test with Maven (aggregate coverage)
        if: contains(matrix.java, '25')
        run: ./mvnw clean test -Paggregate-coverage -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Coverage
        if: always() && contains(matrix.java, '25') && contains(matrix.os, 'macos-15')
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: oshi-benchmark/target/site/jacoco-aggregate/jacoco.xml
          flags: macos
