# CI on NetBSD
name: NetBSD CI

on:
  workflow_dispatch:
  push:
    branches:
      - netbsd-port

jobs:
  test-netbsd:
    name: Test JDK 11, NetBSD
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Test in NetBSD
        id: test-netbsd
        uses: vmactions/netbsd-vm@v1
        with:
          release: "10.1"
          usesh: true
          prepare: |
            pkg_add curl
            pkg_add openjdk11
            pkg_add java-jna
          run: |
            set -ex
            export JAVA_HOME=/usr/pkg/java/openjdk11
            export PATH=$JAVA_HOME/bin:$PATH
            export JAVA_TOOL_OPTIONS="-Djna.boot.library.path=/usr/pkg/lib"
            java -version
            mount -t procfs procfs /proc 2>/dev/null || true
            ./mvnw clean test -B -Djacoco.skip=true
