name: Site

on:
  workflow_dispatch:
  push:
    branches:
      - site
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

permissions:
  contents: write

jobs:
  build:
    if: github.repository_owner == 'oshi'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          cache: maven
          distribution: temurin
          java-version: 25
      - name: Cache NVD database
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-db
      - name: Build site
        run: ./mvnw site site:stage -Djacoco.skip=true -DskipTests -B --settings ./.mvn/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      - name: Deploy Site to gh-pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          branch: gh-pages
          folder: target/staging
