# CI on Unix OS 
# Separated from main CI matrix to reduce churn on failures due to infra
name: Unix CI

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  # Runs current branch on FreeBSD 10.0.1 in a VM
  # Cirrus CI tests 11.4 and 12.1 and 13.0
  testfreebsd:
    runs-on: macos-latest
    name: Test JDK 8, freebsd
    steps:
      - uses: actions/checkout@v2
      - name: Test in FreeBSD
        id: test-freebsd
        uses: vmactions/freebsd-vm@v0.1.5
        with:
          usesh: true
          prepare: |
            pkg install -y curl
            pkg install -y openjdk8
          run: |
            ./mvnw test -B -Djacoco.skip=true

  # Runs current branch on Solaris 11.4 in a VM
  testsolaris:
    runs-on: macos-latest
    name: Test JDK 8, solaris
    steps:
      - uses: actions/checkout@v2
      - name: Test in Solaris
        id: test-solaris
        uses: vmactions/solaris-vm@v0.0.3
        with:
          prepare: |
            pkg install jdk-8
          run: |    
            ./mvnw test -B -Djacoco.skip=true
                      

  # SSH into AIX server and run test on AIX 7.1
  # Configured to pull latest from oshi master branch
  # To test on a PR, log into the aix server and create a new branch
 #temporarily disabled due to polarhome outage
 #testaix:
 #   runs-on: ubuntu-latest
 #   name: Test JDK 8, aix
 #   steps:
 #   - name: Test in AIX
 #     uses: appleboy/ssh-action@master    
 #     with:
 #       host: gate.polarhome.com
 #       username: oshi
 #       password: ${{ secrets.AIX_OSHI_PW }}
 #       port: 775
 #       script_stop: true
 #       command_timeout: 75m
 #       script: |
 #         source .profile
 #         source .bashrc
 #         cd ~/git/oshi
 #         git checkout master
 #         git reset --hard HEAD~2
 #         git pull
 #         mvn clean test -B -Djacoco.skip=true
          

  # SSH into OpenBSD server and run test on OpenBSD 6.8 32-bit
  # Configured to pull latest from oshi master branch
  # To test on a PR, log into the openbsd server and create a new branch
  testopenbsd:
    runs-on: ubuntu-latest
    name: Test JDK 8, openbsd
    steps:
    - name: Test in OpenBSD
      uses: appleboy/ssh-action@master    
      with:
        host: ${{ secrets.OPENBSD_OSHI_DOMAIN }}
        username: oshi
        password: ${{ secrets.OPENBSD_OSHI_PW }}
        port: 22
        script_stop: true
        command_timeout: 15m
        script: |
          cd ~/git/oshi
          git checkout master
          doas git reset --hard HEAD~2
          doas git pull
          doas mvn clean
          mvn test -B -Djacoco.skip=true
          doas mvn test -B -Djacoco.skip=true
          