# Test FreeBSD, Solaris and AIX
name: Unix Java CI

on: 
  workflow_dispatch:
  schedule:
    - cron: "30 9 1 * *" # monthly on 1st at 09:30 UTC

jobs:
  # This tends to work reliably
  # After FreeBSD code changes, reactivate Cirrus CI temporarily
  testfreebsd:
    runs-on: macos-latest
    name: Test JDK 8, freebsd
    steps:
      - uses: actions/checkout@v2
      - name: Test in FreeBSD
        id: test-freebsd
        uses: vmactions/freebsd-vm@v0.0.9
        with:
          usesh: true
          prepare: |
            pkg install -y curl
            pkg install -y openjdk8
          run: |
            ./mvnw test -B

  # This gets through the mvn test part but forks stay alive without timeout
  # Timeout always exits with failed status
  testsolaris:
    runs-on: macos-latest
    name: Test JDK 8, solaris
    steps:
      - uses: actions/checkout@v2
      - name: Test in Solaris
        id: test-solaris
        uses: vmactions/solaris-vm@v0.0.1
        with:
          prepare: |
            pkg install jdk-8
          run: |
            ./mvnw test -B -Djacoco.skip=true -Dsurefire.timeout=300

  # SSH into AIX server and run test
  # Configured to pull latest from oshi master branch
  testaix:
    runs-on: ubuntu-latest
    name: Test JDK 8, aix
    steps:
    - name: Test in AIX
      uses: appleboy/ssh-action@master    
      with:
        host: gate.polarhome.com
        username: oshi
        password: ${{ secrets.AIX_OSHI_PW }}
        port: 775
        script_stop: true
        command_timeout: 45m
        script: |
          source .profile
          source .bashrc
          cd ~/git/oshi
          git reset --hard HEAD
          git pull
          mvn clean test -B -Djacoco.skip=true
          
          
          
          
