# Full CI matrix on all pushes to master branch
name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

permissions:
  contents: read

jobs:
  # Runs current branch with multiple JDKs
  testmatrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [21, 25, 26]
        os: [windows-2022, windows-2025]
      fail-fast: false
    name: JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Test with Maven
        if: ${{ !contains(matrix.java, '25') }}
        run: ./mvnw clean test -B
      - name: Test with Maven (aggregate coverage)
        if: contains(matrix.java, '25')
        run: ./mvnw clean test -Paggregate-coverage -B
      - name: Upload Coverage
        if: always() && contains(matrix.java, '25') && contains(matrix.os, 'windows-2022')
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: oshi-benchmark/target/site/jacoco-aggregate/jacoco.xml
          flags: windows
